language: erlang
script: make

otp_release:
  - 17.4

branches:
  only:
    - master
    - develop

before_install:
  - gem install fpm
  - gem install package_cloud

after_success:
  - fpm --verbose -s dir -t rpm --name $(bin/app) -v $(bin/version) --prefix /opt _rel
  - package_cloud push shortishly/lighthouse/el/7 $(bin/app)-$(bin/version).x86_64.rpm
  